paths:
  /customer/register:
    post:
      summary: Register a new Customer
      tags:
        - Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        200:
          description: Customer registered successfully
        400:
          description: Invalid input
        500:
          description: Internal server error
  /customer/me:
    get:
      summary: Get Customer details
      tags: 
        - Customer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Customer details
        '404':
          description: Customer not found
        '500':
          description: Internal server error
    put:
      summary: Update Customer details
      tags: 
        - Customer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                hp:
                  type: string
                alamat:
                  type: string
                img:
                  type: string
      responses:
        '200':
          description: Customer details updated successfully
        '500':
          description: Internal server error
